member/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('', views.CreateUserView.as_view(), name='registration'),
    path('acc', views.Newview.as_view(), name='newregistration'),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'


urlpatterns = [
    path('question_crepate/', views.PollsCreate.as_view(), name='createview'),
    path('login/', views.Login.as_view(), name='login'),
    path('answer_create/', views.PollsCreateChoice.as_view(), name='createchoise'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
    # path('<str:slugok>/', views.post_detail, name='detail')
]

tania_proect/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', views.new),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
]

member/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import EmailField


class NewCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse
from django.utils import timezone
from datetime import timedelta


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now_add= True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        self.slug = slugify(self.question_text)[:10]
        super(Question, self).save(*args, **kwargs)

    def was_published_recently(self):
        curent_time = timezone.now()
        day_ago = curent_time - timedelta(days=1)
        return day_ago < self.pub_date <curent_time

    def get_absolute_url(self):
        return reverse('polls:detail', args=[str(self.slug)])


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def get_absolute_url(self):
      return reverse('polls:detail', args=(self.question.id,))


class UsersChoise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)


class Meta:
    unique_together = ('user_id', 'choice_id')

member/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import forms
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .models import NewCreationForm


class CreateUserView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('polls:index')
    template_name = 'member/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context['form'].errors,'context')
        return context

    def post(self, request, *args, **kwargs):
        res = super().post(request, *args, **kwargs)
        if self.object:
            login(user=self.object, request=request)
            print(self.object)
        # form_kwargs = self.get_form_kwargs()
        # username = form_kwargs['data']['username']
        # user = User.objects.get(username=username)
        # login(user=user, request=request)
        return res


class Newview(CreateView):
    form_class = NewCreationForm
    success_url = reverse_lazy('polls:index')
    template_name = 'member/index2.html'

polls/views.py
from datetime import datetime

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from .models import Choice, Question, UsersChoise
from django.http import HttpResponseRedirect
from django.shortcuts import render


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_cindex': latest_question_list}
#     return render(request, 'polls/index.html', context)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_cindex'
    queryset = Question.objects.all()

    # def get_queryset(self):
    #     """Return the last five published questions."""
    #     return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


#
#

#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


# def post_detail(request, slugok):
#     question = get_object_or_404(Question, slug=slugok)
#     return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_choices = UsersChoise.objects.filter(choice__question=self.object)
        result = {}
        vsi = Choice.objects.filter(question_id=self.object.id)
        for choice in vsi:
            result[choice.choice_text] = 0

        for user_choice in user_choices:
            result[user_choice.choice.choice_text] += 1

        context['result'] = result
        return context


def time(priniatu):
    def we(*args, **kwargs):
        start = datetime.now()
        result = priniatu(*args, **kwargs)
        print(datetime.now() - start)
        return result
    return we


def login(zalogin):
    def user(*args, **kwargs):
        wsg = args[0]
        if wsg.user.is_authenticated:
            print(wsg.user.is_authenticated)
            result = zalogin(*args, **kwargs)
            return result
        else:
            return redirect(reverse('polls:index'))

    return user


@login
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        avalible_choices = question.choice_set.all().values_list('id', flat=True)
        answered_already = UsersChoise.objects.filter(choice_id__in=avalible_choices, user_id=request.user.id).exists()
        if answered_already:
            messages.add_message(request, messages.ERROR, 'You already vote')
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        UsersChoise.objects.create(user_id=request.user.id, choice_id=selected_choice.id)
        messages.add_message(request, messages.SUCCESS, 'You just voted, thanks')

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))





class PollsCreate(CreateView):
    model = Question
    fields = ['question_text']


class PollsCreateChoice(CreateView):
    model = Choice
    fields = ['question', 'choice_text']


class Login(LoginView):
    template_name = 'polls/login.html'

tania_proect/views.py
from django.http import HttpResponse


def new(request):
    return HttpResponse("first")

member/templates/member/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static "member/signin.css" %}" type="text/css" media="screen">
  </head>
  <body class="text-center">
  {% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
    <form class="form-signin"action="." method="POST">
        {%csrf_token%}
  <img class="mb-4" src="{% static "member/bootstrap-solid.svg.jpg" %}" alt="" width="72" height="72">

  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

  <label for="id_username" class="sr-only">Email address</label>
  <input type="text" id="id_username" name="username" class="form-control" placeholder="Username" required autofocus>

  <label for="id_password1" class="sr-only">Password</label>
  <input type="password" id="id_password1" name="password1" class="form-control" placeholder="Password" required>

  <label for="id_password2" class="sr-only">Password</label>
  <input type="password" id="id_password2" name="password2" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Погодитись на сервіс
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>
</body>
</html>

member/templates/member/index2.html
 {% load static %}
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

    <!-- Bootstrap core CSS -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static "member/signin.css" %}" type="text/css" media="screen">
  </head>
  <body class="text-center">
  {% if form.errors %}<p><strong>{{ form.errors }}</strong></p>{% endif %}
    <form class="form-signin"action="." method="POST">
        {%csrf_token%}
  <img class="mb-4" src="{% static "member/bootstrap-solid.svg.jpg" %}" alt="" width="72" height="72">

  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

  <label for="id_username" class="sr-only">Email address</label>
  <input type="text" id="id_username" name="username" class="form-control" placeholder="Username" required autofocus>

  <label for="id_password1" class="sr-only">Password</label>
  <input type="password" id="id_password1" name="password1" class="form-control" placeholder="Password" required>

  <label for="id_password2" class="sr-only">Password</label>
  <input type="password" id="id_password2" name="password2" class="form-control" placeholder="Password" required>

  <label for="id_email" class="sr-only">Password</label>
  <input type="text" id="id_email" name="email" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Погодитись на сервіс
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>
</body>
</html>

member/templates/member/registration.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="реєстрація">
</form>

polls/templates/polls/choice_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_cindex %}
    <ul>
    {% for question in latest_question_cindex %}
       <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'polls:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}

polls/templates/polls/question_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<!--<ul>-->
<!--{% for choice in question.choice_set.all %}-->
<!--    <li>{{ choice.choice_text }} &#45;&#45; {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>-->
<!--{% endfor %}-->
<!--</ul>-->

<ul>
{% for choice, votes in result.items %}
    <li>{{ choice}} -- голоси {{ votes}}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}